project:
  type: website
  output-dir: docs

website:
  title: "Freya Olsson"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - publications.qmd
      - research.qmd
  

format:
  html:
    theme: litera
    css: styles.css
    toc: true
    link-external-newwindow: true

editor: visual

